name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
        BUILD_BRANCH: gh-pages
        BUILD_DIR: ${HOME}/build
    steps:
      - name: Checkout current branch
        uses: actions/checkout@master
      - name: Make HTML for GitHub Pages
        uses: docker://mitinarseny/panmake:2.7.3
        with:
          entrypoint: make
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Pages Deploy Action"
          git checkout gh-pages || (git checkout --orphan gh-pages && git rm -rf .)
          mv ${BUILD_DIR}/{.,}* ./
          [ -z "$(git status --porcelain)" ] && echo "Pages haven't changed' && "exit 0
          git add .
          git commit -m "Deploying GitHub Pages from ${GITHUB_REF}:${GITHUB_SHA}" --quiet
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" ${BUILD_BRANCH}
