name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
        BUILD_BRANCH: gh-pages
    steps:
      - name: Checkout current branch
        uses: actions/checkout@master
      - name: Make HTML for GitHub Pages
        uses: docker://mitinarseny/panmake:2.7.3
        with:
          entrypoint: make
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Pages Deploy Action"
          git checkout master
          git add -f build/
          git commit -m "Deploying GitHub Pages" --quiet
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" $(git subtree split --prefix build ${GITHUB_REF}):${BUILD_BRANCH} --force
